GET http://localhost:3000/cars

###

GET http://localhost:3000/cars/4

###

DELETE http://localhost:3000/cars/5

###

GET http://localhost:3000/cars?carId=1&Say=hi

###

POST http://localhost:3000/cars
Content-Type: application/json

{
  "title": "asdasd",
  "image": "https://picsum.photos/id/1003/1181/1772",
  "price": 1000,
  "number_plates": "sdsd"
}